// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuK3AWYfeMiGLAJZ244cnJH1y8OVSYqL0',
    appId: '1:838459085498:web:94ffcf25fa0e6c2ff56883',
    messagingSenderId: '838459085498',
    projectId: 'chat-app-ff3fe',
    authDomain: 'chat-app-ff3fe.firebaseapp.com',
    storageBucket: 'chat-app-ff3fe.appspot.com',
    measurementId: 'G-2ZTWHGLP7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc_8pjr0ZOGYBYqrkhrnulxlsTTy-grkc',
    appId: '1:838459085498:android:509ee416927cf918f56883',
    messagingSenderId: '838459085498',
    projectId: 'chat-app-ff3fe',
    storageBucket: 'chat-app-ff3fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_7i8EWxVKkI5xZbCXqOiCxCPEGJEqy14',
    appId: '1:838459085498:ios:c1957393c6f30eadf56883',
    messagingSenderId: '838459085498',
    projectId: 'chat-app-ff3fe',
    storageBucket: 'chat-app-ff3fe.appspot.com',
    iosClientId: '838459085498-3a5acvl0i0mqacr5kdlauhj2q7b29k8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_7i8EWxVKkI5xZbCXqOiCxCPEGJEqy14',
    appId: '1:838459085498:ios:2af861a29661a958f56883',
    messagingSenderId: '838459085498',
    projectId: 'chat-app-ff3fe',
    storageBucket: 'chat-app-ff3fe.appspot.com',
    iosClientId: '838459085498-kgkjg911ej3ucnijgoikkt4anod1equi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplication.RunnerTests',
  );
}
